name: Unit-Test
on:
  push:
    branches:
      - Feature/UnitTest
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run
        run: |
          pytest --maxfail=1 --disable-warnings -q